In [2]:
import pandas as pd
import numpy as np
from urllib.request import urlopen   
from zipfile import ZipFile
import os

In [3]:
URL = 'https://s3.amazonaws.com/capitalbikeshare-data/2011-capitalbikeshare-tripdata.zip'
url = urlopen(URL)
output = open('zipFile.zip','wb')
output.write(url.read())
output.close()
df = pd.read_csv('zipFile.zip')
os.remove('zipFile.zip')

In [4]:
# extract the month & day of the week for each ride
# & also the minute (over 24 hours i.e. between 0 and 24*60)

tmp = df['Start date'].str.split('-',expand=True)
df['Month'] = tmp[1].astype(int)
tmp = tmp[2].str.split(' ',expand=True)
df['Day'] = tmp[0].astype(int)
tmp = tmp[1].str.split(':',expand=True)
df['Minute'] = 60 * tmp[0].astype(int) + tmp[1].astype(int)
df['Day of week'] = (4 + df['Day'] +\
   np.array([0,31,28,31,30,31,30,31,31,30,31,30]).cumsum()[df.Month-1])%7
df.Duration = np.log(df.Duration)

# public holidays: 
# labor day, columbus day, halloween, veterans day, thanksgiving +/- 1 day
df['Holiday'] = ((df['Month']==9)&(df['Day']==5))| ((df['Month']==10)&(df['Day']==10)) | \
    ((df['Month']==10)&(df['Day']==31))| ((df['Month']==11)&(np.abs(df['Day']-24)<=1))

df = df[(df['Day of week'] <= 4) & (df.Month >= 9) & (df.Month <= 11)  & (df.Holiday == False)]
# keep only regular weekdays in sept & nov (train) or oct (test)

In [5]:
df

Duration           Start date             End date  \
791482   7.015712  2011-09-01 00:02:00  2011-09-01 00:20:34   
791483   7.122867  2011-09-01 00:02:04  2011-09-01 00:22:44   
791484   8.534444  2011-09-01 00:02:51  2011-09-01 01:27:39   
791485   8.531885  2011-09-01 00:02:53  2011-09-01 01:27:28   
791486   6.916715  2011-09-01 00:04:24  2011-09-01 00:21:14   
...           ...                  ...                  ...   
1140450  7.019297  2011-11-30 23:55:41  2011-12-01 00:14:19   
1140451  6.665684  2011-11-30 23:55:43  2011-12-01 00:08:49   
1140452  5.505332  2011-11-30 23:57:51  2011-12-01 00:01:57   
1140453  4.941642  2011-11-30 23:58:27  2011-12-01 00:00:47   
1140454  6.646391  2011-11-30 23:59:51  2011-12-01 00:12:41   

         Start station number                         Start station  \
791482                  31503                 Florida Ave & R St NW   
791483                  31218        L'Enfant Plaza / 7th & C St SW   
791484                  31217     USDA / 12th & Independence Ave SW   
791485                  31217     USDA / 12th & Independence Ave SW   
791486                  31200  Massachusetts Ave & Dupont Circle NW   
...                       ...                                   ...   
1140450                 31223     Convention Center / 7th & M St NW   
1140451                 31200  Massachusetts Ave & Dupont Circle NW   
1140452                 31213                        17th & K St NW   
1140453                 31202                        14th & R St NW   
1140454                 31228                         8th & H St NW   

         End station number                           End station Bike number  \
791482                31103                  16th & Harvard St NW      W00977   
791483                31214                 17th & Corcoran St NW      W00590   
791484                31217     USDA / 12th & Independence Ave SW      W00579   
791485                31217     USDA / 12th & Independence Ave SW      W00832   
791486                31200  Massachusetts Ave & Dupont Circle NW      W00749   
...                     ...                                   ...         ...   
1140450               31104           Adams Mill & Columbia Rd NW      W00288   
1140451               31101                        14th & V St NW      W00402   
1140452               31214                 17th & Corcoran St NW      W00778   
1140453               31101                        14th & V St NW      W00645   
1140454               31212                        21st & M St NW      W00751   

        Member type  Month  Day  Minute  Day of week  Holiday  
791482       Member      9    1       2            3    False  
791483       Member      9    1       2            3    False  
791484       Casual      9    1       2            3    False  
791485       Casual      9    1       2            3    False  
791486       Member      9    1       4            3    False  
...             ...    ...  ...     ...          ...      ...  
1140450      Casual     11   30    1435            2    False  
1140451      Casual     11   30    1435            2    False  
1140452      Member     11   30    1437            2    False  
1140453      Member     11   30    1438            2    False  
1140454      Member     11   30    1439            2    False  

[224619 rows x 14 columns]

In [6]:
def duration_mean_by_time(group):
    # estimate E[log(Duration)] & Var[log(Duration)] 
    # for each time of day (in minutes), for that particular route
    n = len(group)
    h = 20 # bandwidth in minutes
    K = np.exp(-np.power(12*60 - np.abs(np.abs(group.Minute[:,None] - group.Minute[None,:])\
               - 12*60),2)/2/h**2) * np.array(group.Month != 10)
    # K(i,j) is nonzero only for j in training set
    group['K_weights_total'] = np.dot(K, np.ones(n))
    group['Duration_mean'] = np.divide(np.dot(K, group.Duration), group.K_weights_total, \
            out=np.zeros(n), where= (group.K_weights_total!=0))
    group['Duration_var'] = np.divide(np.dot(K, np.power(group.Duration,2)), group.K_weights_total, \
            out=np.zeros(n), where= (group.K_weights_total!=0)) - np.power(group.Duration_mean,2)
    return group

In [7]:
df = df.groupby(['Start station number', 'End station number']).apply(duration_mean_by_time)
df1 = df[(df.Month == 10) & (df.K_weights_total >= 20)] # test set

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:7: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  import sys


In [8]:
df

Duration           Start date             End date  \
791482   7.015712  2011-09-01 00:02:00  2011-09-01 00:20:34   
791483   7.122867  2011-09-01 00:02:04  2011-09-01 00:22:44   
791484   8.534444  2011-09-01 00:02:51  2011-09-01 01:27:39   
791485   8.531885  2011-09-01 00:02:53  2011-09-01 01:27:28   
791486   6.916715  2011-09-01 00:04:24  2011-09-01 00:21:14   
...           ...                  ...                  ...   
1140450  7.019297  2011-11-30 23:55:41  2011-12-01 00:14:19   
1140451  6.665684  2011-11-30 23:55:43  2011-12-01 00:08:49   
1140452  5.505332  2011-11-30 23:57:51  2011-12-01 00:01:57   
1140453  4.941642  2011-11-30 23:58:27  2011-12-01 00:00:47   
1140454  6.646391  2011-11-30 23:59:51  2011-12-01 00:12:41   

         Start station number                         Start station  \
791482                  31503                 Florida Ave & R St NW   
791483                  31218        L'Enfant Plaza / 7th & C St SW   
791484                  31217     USDA / 12th & Independence Ave SW   
791485                  31217     USDA / 12th & Independence Ave SW   
791486                  31200  Massachusetts Ave & Dupont Circle NW   
...                       ...                                   ...   
1140450                 31223     Convention Center / 7th & M St NW   
1140451                 31200  Massachusetts Ave & Dupont Circle NW   
1140452                 31213                        17th & K St NW   
1140453                 31202                        14th & R St NW   
1140454                 31228                         8th & H St NW   

         End station number                           End station Bike number  \
791482                31103                  16th & Harvard St NW      W00977   
791483                31214                 17th & Corcoran St NW      W00590   
791484                31217     USDA / 12th & Independence Ave SW      W00579   
791485                31217     USDA / 12th & Independence Ave SW      W00832   
791486                31200  Massachusetts Ave & Dupont Circle NW      W00749   
...                     ...                                   ...         ...   
1140450               31104           Adams Mill & Columbia Rd NW      W00288   
1140451               31101                        14th & V St NW      W00402   
1140452               31214                 17th & Corcoran St NW      W00778   
1140453               31101                        14th & V St NW      W00645   
1140454               31212                        21st & M St NW      W00751   

        Member type  Month  Day  Minute  Day of week  Holiday  \
791482       Member      9    1       2            3    False   
791483       Member      9    1       2            3    False   
791484       Casual      9    1       2            3    False   
791485       Casual      9    1       2            3    False   
791486       Member      9    1       4            3    False   
...             ...    ...  ...     ...          ...      ...   
1140450      Casual     11   30    1435            2    False   
1140451      Casual     11   30    1435            2    False   
1140452      Member     11   30    1437            2    False   
1140453      Member     11   30    1438            2    False   
1140454      Member     11   30    1439            2    False   

         K_weights_total  Duration_mean  Duration_var  
791482          1.000000       7.015712  5.606182e-12  
791483          1.000000       7.122867  0.000000e+00  
791484          2.547139       8.589614  1.198342e-02  
791485          2.547139       8.589614  1.198342e-02  
791486          1.045072       6.875690  4.847312e-02  
...                  ...            ...           ...  
1140450         1.000003       7.019297  3.605498e-08  
1140451         7.533130       6.368584  3.611326e-02  
1140452         3.320573       5.863383  1.541332e-01  
1140453        10.348407       5.183123  1.072650e-01  
1140454         1.002814     

In [36]:
# generate CPT copies of X when the conditional distribution is Gaussian
# i.e. X | Z=Z_i ~ N(mu[i],sig2[i])
def generate_X_CPT_gaussian(nstep,M,X0,mu,sig2):
    log_lik_mat = - np.power(X0,2)[:,None] * (1/2/sig2)[None,:] + X0[:,None] * (mu/sig2)[None,:]
    print(log_lik_mat)
    Pi_mat = generate_X_CPT(nstep,M,log_lik_mat)
    return X0[Pi_mat]

# generate CPT copies of X in general case
# log_lik_mat[i,j] = q(X[i]|Z[j]) where q(x|z) is the conditional density for X|Z
def generate_X_CPT(nstep,M,log_lik_mat,Pi_init=[]):
    n = log_lik_mat.shape[0]
    if len(Pi_init)==0:
        Pi_init = np.arange(n,dtype=int)
    Pi_ = generate_X_CPT_MC(nstep,log_lik_mat,Pi_init)
    Pi_mat = np.zeros((M,n),dtype=int)
    for m in range(M):
        Pi_mat[m] = generate_X_CPT_MC(nstep,log_lik_mat,Pi_)
    return Pi_mat

def generate_X_CPT_MC(nstep,log_lik_mat,Pi):
    n = len(Pi)
    npair = np.floor(n/2).astype(int)
    for istep in range(nstep):
        perm = np.random.choice(n,n,replace=False)
        inds_i = perm[0:npair]
        inds_j = perm[npair:(2*npair)]
        # for each k=1,...,npair, decide whether to swap Pi[inds_i[k]] with Pi[inds_j[k]]
        log_odds = log_lik_mat[Pi[inds_i],inds_j] + log_lik_mat[Pi[inds_j],inds_i] \
            - log_lik_mat[Pi[inds_i],inds_i] - log_lik_mat[Pi[inds_j],inds_j]
        swaps = np.random.binomial(1,1/(1+np.exp(-np.maximum(-500,log_odds))))
        Pi[inds_i], Pi[inds_j] = Pi[inds_i] + swaps*(Pi[inds_j]-Pi[inds_i]), Pi[inds_j] - \
            swaps*(Pi[inds_j]-Pi[inds_i])   
    return Pi

In [9]:
# create CRT & CPT copies

ntrial = 10
M = 1000 # number of copies
n = len(df1)
nstep = 50 # number of steps in the MC for the CPT

print('Total number training data points: n_train = '+ str((df.Month!=10).sum()))
print('Total number test data points (after screening): n = '+str(n))

X = np.array(df1.Duration)
X_CRT = np.zeros((ntrial,M,n))
X_CPT = np.zeros((ntrial,M,n))

Duration_mean = np.array(df1.Duration_mean)
Duration_var = np.maximum(1e-12,np.array(df1.Duration_var))

for itrial in range(ntrial):
    np.random.seed(12345 + itrial)
    X_CRT[itrial] = np.random.normal(size=(M,n)) * np.sqrt(Duration_var) + Duration_mean
    X_CPT[itrial] = generate_X_CPT_gaussian(nstep,M,X,Duration_mean,Duration_var)

Total number training data points: n_train = 149912
Total number test data points (after screening): n = 7346


In [10]:
def corr_mat_vec(x,y):
    # x is a ntrial-by-M-by-n numpy array, y is a length-n numpy array
    # return ntrial-by-M matrix of correlations of each x with y
    x = ((x.transpose((2,0,1)) - x.mean(2))/np.sqrt(x.var(2))).transpose((1,2,0))
    y = (y - y.mean(0))/np.sqrt(y.var(0))
    return np.dot(x,y)/len(y)

def corr_mat_vec_cat(x,y):
    # x is a ntrial-by-M-by-n numpy array, y is a length-n numpy array
    # y is a categorical variable with c many categories
    # return ntrial-by-M-by-c array of correlations 
    # between each x and each y indicator
    yvals = np.unique(y)
    tmp = np.zeros((x.shape[0],x.shape[1],len(yvals)))
    for i in range(len(yvals)):
        tmp[:,:,i] = corr_mat_vec(x,(y==yvals[i]))
    return tmp

def str_mean_se(vec):
    return str(np.round(vec.mean(),4)) + ' (' + str(np.round(np.sqrt(vec.var()/len(vec)),4)) + ')'

In [11]:
# Response 1: member (1) or nonmember i.e. 'casual' (0)
Y1 = np.array(df1['Member type'] == 'Member')
T = np.abs(corr_mat_vec((X - Duration_mean).reshape((1,1,-1)),Y1))
T_CRT = np.abs(corr_mat_vec((X_CRT - Duration_mean),Y1))
T_CPT = np.abs(corr_mat_vec((X_CPT - Duration_mean),Y1))
p_CRT = (1 + (T_CRT>=T).sum(1))/(1+M)
p_CPT = (1 + (T_CPT>=T).sum(1))/(1+M)

print('Response Y1 = member type: p-value = ' +\
      str_mean_se(p_CPT) + ' for CPT, ' + str_mean_se(p_CRT) + ' for CRT')

Response Y1 = member type: p-value = 0.001 (0.0) for CPT, 0.001 (0.0) for CRT


In [12]:
# Response 2: date
Y2 = np.array(df1['Day'])
T = np.abs(corr_mat_vec((X - Duration_mean).reshape((1,1,-1)),Y2))
T_CRT = np.abs(corr_mat_vec((X_CRT - Duration_mean),Y2))
T_CPT = np.abs(corr_mat_vec((X_CPT - Duration_mean),Y2))
p_CRT = (1 + (T_CRT>=T).sum(1))/(1+M)
p_CPT = (1 + (T_CPT>=T).sum(1))/(1+M)

print('Response Y2 = date: p-value = ' +\
      str_mean_se(p_CPT) + ' for CPT, ' + str_mean_se(p_CRT) + ' for CRT')

Response Y2 = date: p-value = 0.1217 (0.0028) for CPT, 0.1293 (0.0032) for CRT


In [13]:
# Response 3: day of week
Y3 = np.array(df1['Day of week'])
T = np.abs(corr_mat_vec_cat((X-Duration_mean).reshape((1,1,-1)),Y3)).max(2)
T_CRT = np.abs(corr_mat_vec_cat((X_CRT - Duration_mean),Y3)).max(2)
T_CPT = np.abs(corr_mat_vec_cat((X_CPT - Duration_mean),Y3)).max(2)
p_CRT = (1 + (T_CRT>=T).sum(1))/(1+M)
p_CPT = (1 + (T_CPT>=T).sum(1))/(1+M)

print('Response Y3 = day of week: p-value = ' +\
      str_mean_se(p_CPT) + ' for CPT, ' + str_mean_se(p_CRT) + ' for CRT')

Response Y3 = day of week: p-value = 0.2016 (0.0044) for CPT, 0.2063 (0.0032) for CRT


In [20]:
df1['Day of week']

922703     0
922708     0
922713     0
922716     0
922728     0
          ..
1031784    4
1031795    4
1031802    4
1031808    4
1031831    4
Name: Day of week, Length: 7346, dtype: int64

In [41]:
generate_X_CPT_gaussian(nstep=10,M=10,X0=np.array([1,2,3,4,5,6,7,8,9]),
                        mu=np.array([3,3,3,3,3,7,7,7,7,7]),
                        sig2=np.array([1,1,1,1,1,1,1,1,1,1])
                       )


[[  2.5   2.5   2.5   2.5   2.5   6.5   6.5   6.5   6.5   6.5]
 [  4.    4.    4.    4.    4.   12.   12.   12.   12.   12. ]
 [  4.5   4.5   4.5   4.5   4.5  16.5  16.5  16.5  16.5  16.5]
 [  4.    4.    4.    4.    4.   20.   20.   20.   20.   20. ]
 [  2.5   2.5   2.5   2.5   2.5  22.5  22.5  22.5  22.5  22.5]
 [  0.    0.    0.    0.    0.   24.   24.   24.   24.   24. ]
 [ -3.5  -3.5  -3.5  -3.5  -3.5  24.5  24.5  24.5  24.5  24.5]
 [ -8.   -8.   -8.   -8.   -8.   24.   24.   24.   24.   24. ]
 [-13.5 -13.5 -13.5 -13.5 -13.5  22.5  22.5  22.5  22.5  22.5]]


array([[1, 3, 2, 5, 4, 8, 6, 7, 9],
       [4, 5, 2, 3, 1, 8, 9, 7, 6],
       [3, 1, 2, 4, 5, 9, 8, 7, 6],
       [3, 4, 2, 1, 5, 8, 7, 6, 9],
       [1, 4, 2, 5, 3, 9, 7, 6, 8],
       [3, 2, 5, 1, 4, 7, 8, 6, 9],
       [2, 3, 5, 4, 1, 8, 9, 6, 7],
       [2, 1, 5, 3, 4, 6, 9, 8, 7],
       [2, 1, 5, 3, 4, 8, 7, 6, 9],
       [1, 5, 2, 4, 3, 8, 6, 7, 9]])

In [23]:
Duration_var

array([0.00469523, 0.01047113, 0.00868368, ..., 0.09998288, 0.09111724,
       0.0955423 ])